import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const inter = localFont({
  src: "../fonts/Inter.ttf",
  variable: "--font-inter",
});

const geistMono = localFont({
  src: "../fonts/Geist-Mono.ttf",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Client Management",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${geistMono.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
